sudo: required
services:
  - docker

before_install:
  - docker build -t yoshiki1116/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true yoshiki1116/docker-react-test npm run test
